### ISSUE TITLE
Should we close this repo?

### ISSUE THREAD

**Issue by samccann** [ansible-collections/.github#5]
Is this repo actually used anywhere? It hasn't had activity for three years and not sure it's doing anything.

**Comment by samccann** [comment]
@mariolenz @dmsimard ... do you know if this repo needs to stick around? We're trying to clean up/archive repos no longer in use.

**Comment by mariolenz** [comment]
It looks like I felt the urge to contribute to this repo (#4) but forgot about it. Actually, I really don't know if this is still needed or used somewhere.

I'm not 100% sure what this repo is for, but there's a [.github/settings.yml in community.vmware](https://github.com/ansible-collections/community.vmware/blob/9c9d760ab3a8ea2d533b2e4b88c48bab8469c28d/.github/settings.yml) which looks like it pulls in this repo. Also in [community.general](https://github.com/ansible-collections/community.general/blob/bc7ad0f0ea6e6a7382488e99d0a54ea84324269f/.github/settings.yml).

I suggest to open a topic / thread in the forum (if you haven't done this yet) about the future of this repo and mark it to be discussed in the next meeting.

**Comment by samccann** [comment]
The answer from the[ forum topic](https://forum.ansible.com/t/what-is-ansible-collections-github-repo-used-for/5791) is this is in use across many repos so leave it open.

Thanks!
